#!/usr/bin/env php
<?php
require __DIR__ . '/../../autoload.php';

\DebugHelper::init();
$commandLine = new \DebugHelper\Cli();
try {
    $commandLine->execute($argv);
} catch (\Exception $exception) {
    echo $exception->getMessage() . "\n";
}
