#!/usr/bin/env php
<?php
require __DIR__ . '/../../autoload.php';

use DebugHelper\Cli\ListCommand;
use DebugHelper\Cli\ReadCommand;
use Symfony\Component\Console\Application;

\DebugHelper::init();
$application = new Application();

$application->add(new ReadCommand());
$application->add(new ListCommand());

$application->run();
